name: Maven CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  maven_test:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: maven

      - name: Test with Maven
        run: mvn test

      - name: Upload jacoco results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Jacoco coverage results
          path: target/site/jacoco

      - name: Cache build
        uses: actions/cache@v3
        with:
          key: cached-build-${{ github.sha }}
          path: .

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

  update_dependence_graph:
    needs: [maven_test]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Restore cached build
        uses: actions/cache@v3
        with:
          key: cached-build-${{ github.sha }}
          path: .

      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@v3
